### ISSUE TITLE
Linking against primesieve.dll fails when using cpuInfo

### ISSUE THREAD

**Issue by kimwalisch** [kimwalisch/primesieve#59]
Building a shared primesieve.dll on Windows works fine with CMake >= 3.4. However the global ```cpuInfo``` variable from ```CpuInfo.hpp``` is not exported. This is not a big issue since ```cpuInfo``` is not part of primesieve's public API.

However the primesieve console application and one of the tests use ```cpuInfo``` which causes linker errors when linking against primesieve.dll.

```cmd
cmdoptions.obj : error LNK2019: unresolved external symbol "class primesieve::CpuInfo const primesieve::cpuInfo" (?cpuInfo@primesieve@@3VCpuInfo@1@B) referenced in function "void __cdecl `anonymous namespace'::optionCpuInfo(void)" (?opt
ionCpuInfo@?A0xfe6d5e28@@YAXXZ) [C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\primesieve.vcxproj]
C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\Release\primesieve.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\primesieve.vcxproj]
Done Building Project "C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\primesieve.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\ALL_BUILD.vcxproj" (default targets) -- FAILED.


Build FAILED.

"C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\primesieve.vcxproj" (default target) (4) ->
(Link target) ->
  cmdoptions.obj : error LNK2019: unresolved external symbol "class primesieve::CpuInfo const primesieve::cpuInfo" (?cpuInfo@primesieve@@3VCpuInfo@1@B) referenced in function "void __cdecl `anonymous namespace'::optionCpuInfo(void)" (?o
ptionCpuInfo@?A0xfe6d5e28@@YAXXZ) [C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\primesieve.vcxproj]
  C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\Release\primesieve.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\kimwa\OneDrive\Documents\GitHub\primesieve\build5\primesieve.vcxproj]

    0 Warning(s)
    2 Error(s)
```

The problem comes from the fact that CMake's ```-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE``` does not export global variables I think.
